sudo: required

services:
  - docker

before_install:
  - ./bin/docker-build
  - ./bin/docker-run "mix local.rebar --force; mix local.hex --force; mix deps.get"

script:
  - ./mix/test-cover

after_script:
  - ./bin/docker-run "mix deps.get --only docs; MIX_ENV=docs mix inch.report"

notifications:
  recipients:
    - dev@lone-cyprus.com
