language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0.5
sudo: false
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix test --cover
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - dev@lone-cyprus.com
